services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - type: remote
        source: rumpl/volume:db
        target: mydbdata:/var/lib/mysql
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      PMA_HOST: db
    networks:
      - net
networks:
  net:
