site_name: Docker Desktop Extensions
theme:
  language: en
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - content.code.annotate
extra:
  generator: false
copyright: Copyright &copy; 2021 Docker, Inc.

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview:
      - Introduction: index.md
  - Tutorials:
      - Create a minimal extension: tutorials/ui-minimal-extension.md
      - Create a graphical extension (ReactJS): tutorials/ui-extension.md
      - Create a VM-service extension: tutorials/vm-service-extension.md
      - Expose a socket/npipe: tutorials/expose-socket-npipe.md
      - Deploy binaries on the host: tutorials/deploy-binaries-on-host.md
  - Extensions:
      - Metadata: extensions/METADATA.md
      - Validation: extensions/validation.md
      - Distribution: extensions/DISTRIBUTION.md
      - Style customization: extensions/style.md
      - Samples:
          - SwimmingWhale: extensions/samples/swimmingwhale/README.md
          - Tailscale: extensions/samples/tailscale/README.md
          - Telepresence: extensions/samples/telepresence/README.md
          - VM UI: extensions/samples/vm-ui/README.md
          - Volumes share: extensions/samples/volumes-share/README.md
  - Developer guide:
      - Overview: dev/overview.md
      - CLI:
          - Usage overview: dev/cli/usage.md
          - Build, test and install an extension: dev/cli/Build, test and install an extension.md
      - UI API:
          - Overview: dev/api/overview.md
