name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Build plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build all
        run: make all
