name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build plugins
    strategy:
      matrix:
        sample: ['swimmingwhale', 'tailscale', 'telepresence', 'vm-ui-plugin']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build sample ${{ matrix.sample }}
        run: cd ${{ matrix.sample }} ; make plugin
